name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  run-tests:
    runs-on: ubuntu-latest

    environment: test

    env:
      FABRIC_WORKSPACE: ${{ vars.FABRIC_WORKSPACE }}
      FABRIC_ORCHESTRATOR: ${{ vars.FABRIC_ORCHESTRATOR }}
      FABRIC_JOB_TIMEOUT: ${{ vars.FABRIC_JOB_TIMEOUT }}

      FAB_SPN_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
      FAB_SPN_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
      FAB_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}

    steps:
    
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Fabric CLI
        run: |
          python -m pip install --upgrade pip
          pip install ms-fabric-cli
          fab --version

      - name: Configure Fabric CLI
        shell: bash
        run: |
          set -euo pipefail
          fab config set encryption_fallback_enabled true
          fab config set mode command_line

      - name: Build DBT project
        shell: bash
        run: |
          set -euo pipefail

          ORCHESTRATOR_PATH="${FABRIC_WORKSPACE}.Workspace/${FABRIC_ORCHESTRATOR}.DataPipeline"

          echo "Ejecutando pipeline de Fabric: $ORCHESTRATOR_PATH"

          fab job run "$ORCHESTRATOR_PATH" \
            --timeout "$FABRIC_JOB_TIMEOUT" \
            --polling_interval 30
